### ISSUE TITLE
Must Discover Themostat after any Restart

### ISSUE THREAD

**Issue by lenp2001** [simplextech/udi-poly-st-nuheat#1]
If I reboot my ISY and or teh Polisy I must go back and sxelect Discover Thermostat to see any information in my "Office" thermostat. The Node is there "Office" after restart but doesn't populate data till I select Discover.

**Comment by simplextech** [comment]
I'll look into it.  Note that after a reboot of the ISY there is no data for anything.  The NodeServer needs to poll Nuheat to get information.  Have you let it sit and go through a polling cycle before hitting 'discover'?

**Comment by lenp2001** [comment]
No I have not given it much time so let’s see if that’s the only reason because if so I apologize for taking up your time. Nice NodeServer
Time to time I get a ground fault (NuHeat tells me its because of voltage spikes) and that creates a fault for the stat and one has to physically push the button on the side. This has happened to me about once a month and it also looks like I am able to turn off the power to the system and back on and that’s equal to pushing the button.
I want to see what clues Ill have that the system has failed when this fault happens so I can trip a smarthome device to turn on and off the power to the floor. Any idea on how I may intercept a ground fault with this nodeserver? Im sure a cold temp on the floor may just be enough as that’s what Im concerned with in the winter because if gone for days I count on this heated floor to help plumbing underneath as well (keep Negative 20 degree temps at bay). I think that would be helpful for others as well. Thanks


 Len
 Owner \ President

 PTACloud LLC
 Office: 815.334.0201
 Cell:     312.833.8215

 Network Administration / VOIP / Cloud Hosting / System Design
P       Please consider the environment before printing. Thank you!

**Comment by simplextech** [comment]
I'm not sure if the ground fault error gets reported.  Let me check with Nuheat and find out.

**Comment by lenp2001** [comment]
Thanks for looking into the Ground Fault, let me know. The discovery though is still an issue on restart. It was restarted and used for well over an hour and I still had to rediscover.

**Comment by lenp2001** [comment]
Just to verify, This morning I opened my Admin panel for the ISY and when I select the Thermostat I want to view there is no dat in there. Every field is empty. I did see data there last night. I have waited 1 hour this morning and checked again and still all empty fields. Doing a Query brings in no data. They do populate the moment I go to ST-Nuheat and ask it to discover but the data is incorrect. I dont know where its getting its data but its the only stat I have. When I make some changes in teh admin panel of the ISY I see them populate into the fields buy my actual thermostat does not update.

**Comment by simplextech** [comment]
Nuheat does not currently report the ground fault or other errors to the API.  That is however planned for future release.

As for the other problems with the restart.  I will look into it and get it resolved.

**Comment by lenp2001** [comment]
I just removed the other issue. It was because the Thermostat wasn’t on my WiFi so it wasn’t updating Nuheat to then update my ISY info.
Thanks for the help. Ill do some small program to just check when the floor temp has gotten under 65 as that will be an indicator that the ground fault has tripped.
Thanks again! Nice program! To bad on the GFP but if added one day that would be great!


 Len
 Owner \ President

 PTACloud LLC
 Office: 815.334.0201
 Cell:     312.833.8215

 Network Administration / VOIP / Cloud Hosting / System Design
P       Please consider the environment before printing. Thank you!

**Comment by simplextech** [comment]
Not connected to Wifi would prevent updates.  I have noticed a issue with some of the values not updating after a ISY reboot.  They are updated but if the values have not changed they do not display anything on the ISY.  I'll update the NodeServer for the next release to force the updates to eliminate blank/missing data in the ISY Admin Console.
